### ISSUE TITLE
Support custom :id attribute

### ISSUE THREAD

**Issue by bvaughn** [treasure-data/redux-search#16]
redux-search currently expects every searchable object to define an `id` property. The [docs mention this](https://github.com/treasure-data/redux-search#overview) but it would be nice if we allow users to customize this attribute on a per-index basis. (I can imagine someone using `uid` instead for example.)

**Comment by bvaughn** [comment]
Going to leave this one open for now, pending feedback/requests from the community.

**Comment by tomauty** [comment]
I'd like this

**Comment by bvaughn** [comment]
Hey @tomauty,

Just so you know- this is currently possible through the use of a custom indexing function. (You can read more about that [here](https://github.com/treasure-data/redux-search/blob/master/docs/reduxSearch.md).)

This issue is just an idea I had about maybe making it simpler to do. (So you didn't have to roll your own indexing function.) Trouble is, I'm not sure of the best API for this. Should the `id` override be a per-resource thing? That seems a little verbose... Should it be global? I think I may be leaning that way.

I'd be interested in hearing more about your use-case. :)

**Comment by tomauty** [comment]
Oh, I actually didn't see that. I would maybe just put a link to that doc in the README somewhere. I'll see if that accomplishes what I'm looking for.

**Comment by bvaughn** [comment]
Going to close this issue for now as I feel like the suggested work around is sufficiently flexible for non-`id` cases. We can always re-open if needed. :D
