### ISSUE TITLE
Scrolling doesn't work as expected

### ISSUE THREAD

**Issue by Sparragus** [treasure-data/redux-search#25]
Scrolling is not working properly. Instead of scrolling the list, it scrolls a single row. (At least on https://treasure-data.github.io/redux-search/)

**Comment by bvaughn** [comment]
Hi @Sparragus,

I think this issue should actually be reported against [react-virtualized](https://github.com/bvaughn/react-virtualized), a library we're using on our demo page to efficiently render the data _after_ redux-search has filtered it. Would you mind filing an issue over there with a little more description? (When you say "scrolling" do you mean scrolling with a mouse-wheel, with a keyboard, etc.)

**Comment by bvaughn** [comment]
Turns out, this is something that required a small CSS fix on this side- but that's been made and deployed. Thanks again for reporting :)

**Comment by Sparragus** [comment]
Cool! Again, happy to contribute with bug reporting. :)
