### ISSUE TITLE
Babel 6

### ISSUE THREAD

**Issue by CurtisHumphrey** [treasure-data/redux-search#31]
I'm getting: Uncaught ReferenceError: regeneratorRuntime is not defined when using Babel 6 in my base project.  Any ideas on a fix?

**Comment by bvaughn** [comment]
Make sure you're including `path/to/browser-polyfill.js` (which includes `babel-runtime/regenerator` for generators/async functions).

**Comment by bvaughn** [comment]
Let me know if the above suggestion resolves your issue, @CurtisHumphrey. :)

**Comment by bvaughn** [comment]
Closing duet o lack of a response. I assume the issue has been resolved. Please feel free to reopen with more information if you're still having this problem :)
