### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by scherler** [treasure-data/redux-search#33]
Hi, I am trying to use the lib but stumble over the examples. :(

https://github.com/treasure-data/redux-search/tree/master/docs

under the section "searchStateSelector" (and as well in the main README - connecting a component)

```
const selectors = createSelector(
  [result, books, text],
  (result, books, text) => ({
    bookIds: result,
    books,
    searchText
  })
)
```

where is books defined? What is it where it is coming from?

As well in the principal readme resourceSelector, you use state.resources where is that coming from?  I do not see that in my integration.

**Comment by bvaughn** [comment]
Hi @scherler,

Sorry for the ambiguity. Writing documentation is hard. :)

I've just updated the docs you mentioned. Hopefully this answers your questions. If not, let me know!

**Comment by scherler** [comment]
Yes, thanks.
