### ISSUE TITLE
babel-plugin-react-transform update 

### ISSUE THREAD

**Issue by scherler** [treasure-data/redux-search#35]
Hi all, 

I am currently playing around with the code and since I banged my head yesterday I started change the  website folder to my project needs including fetching some resources. Since that worked great I just copied the whole folder into my own development and fixed some relative paths to point to the plugin.

That worked like a charm but when pressing the generate data button, I am getting following stacktrace:

´´´
[HMR] Waiting for update signal from WDS...
crash  () {
	    return dispatch(actionCreator.apply(undefined, arguments));
	  } () {
	    return dispatch(actionCreator.apply(undefined, arguments));
	  } [] Object {size: 0, _origin: 0, _capacity: 0, _level: 5, _root: undefined…}  Object {size: 0, _map: Object, _list: Object, __ownerID: undefined, __hash: undefined} Object {size: 0, _map: Object, _list: Object, __ownerID: undefined, __hash: undefined} () {
	    return dispatch(actionCreator.apply(undefined, arguments));
	  } () {
	    return dispatch(actionCreator.apply(undefined, arguments));
	  }
[WDS] Hot Module Replacement enabled.
Uncaught ReferenceError: regeneratorRuntime is not defined
crash  () {
	    return dispatch(actionCreator.apply(undefined, arguments));
	  } () {
	    return dispatch(actionCreator.apply(undefined, arguments));
	  } [] Object {size: 0, _origin: 0, _capacity: 0, _level: 5, _root: undefined…}  Object {size: 0, _map: Object, _list: Object, __ownerID: undefined, __hash: undefined} Object {} () {
	    return dispatch(actionCreator.apply(undefined, arguments));
	  } () {
	    return dispatch(actionCreator.apply(undefined, arguments));
	  }
´´´

´´´
Uncaught ReferenceError: regeneratorRuntime is not definedperformSearch @ main.js:1286(anonymous function) @ main.js:1144dispatch @ main.js:1066(anonymous function) @ main.js:1147(anonymous function) @ main.js:418(anonymous function) @ createStore.js:132dispatch @ createStore.js:131(anonymous function) @ main.js:1146(anonymous function) @ main.js:418(anonymous function) @ createStore.js:132dispatch @ createStore.js:131(anonymous function) @ main.js:1149(anonymous function) @ index.js:9dispatch @ applyMiddleware.js:46(anonymous function) @ resources.js:51(anonymous function) @ index.js:9(anonymous function) @ bindActionCreators.js:14ReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js:71executeDispatch @ EventPluginUtils.js:79executeDispatchesInOrder @ EventPluginUtils.js:102executeDispatchesAndRelease @ EventPluginHub.js:43executeDispatchesAndReleaseTopLevel @ EventPluginHub.js:54forEachAccumulated @ forEachAccumulated.js:23EventPluginHub.processEventQueue @ EventPluginHub.js:259runEventQueueInBatch @ ReactEventEmitterMixin.js:18ReactEventEmitterMixin.handleTopLevel @ ReactEventEmitterMixin.js:34handleTopLevelWithoutPath @ ReactEventListener.js:93handleTopLevelImpl @ ReactEventListener.js:73Mixin.perform @ Transaction.js:136ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy.js:62batchedUpdates @ ReactUpdates.js:94ReactEventListener.dispatchEvent @ ReactEventListener.js:204
´´´

I am using the configuration from https://github.com/scherler/jenkins-plugin-site/tree/nodeInfrastructure (commit 13be2428e11db51bf693275ffcabb51431fccc5b)

I tried to update to update babel to 
+    "babel": "6.3.26",
+   "babel-core": "6.3.26",

**Comment by bvaughn** [comment]
This issue is pretty difficult to understand, but it seems to be related to babel/babelify/issues/28 (or various other places online). It seems like your project is missing [babel-polyfill](https://babeljs.io/docs/usage/polyfill/).

The project you linked to (scherler/jenkins-plugin-site) seems to be installing this polyfill (it's in package.json) and trying to load it (it's in your webpack config) but... I didn't dig any further than that. This  is a webpack or project configuration issue, nothing specific to redux-search.

**Comment by bvaughn** [comment]
PS One of my teammates confirms that he encountered the same problem but adding `import 'babel-polyfill'` to his bootstrapping file fixed it.
