### ISSUE TITLE
Inconsistent naming in docs

### ISSUE THREAD

**Issue by SpencerCDixon** [treasure-data/redux-search#38]
```
const {
  text as searchText,
  result as bookIds
} = getSearchSelectors('books')

const selectors = createSelector(
  [bookIds, books, text],
  (bookIds, books, text) => ({
    bookIds,
    books,
    searchText
  })
)
```

Shouldn't the 'text' inside the array for createSelector be called 'searchText'?

**Comment by bvaughn** [comment]
Ah, good find @SpencerCDixon. I'll update the docs to fix the inconsistency. :)

**Comment by SpencerCDixon** [comment]
haha okay glad that it was actually a typo, was second guessing myself for far too long ha

**Comment by bvaughn** [comment]
Yeah, sorry man. :)

Wish there was a way to auto-test code samples in markdown docs. I make too many silly typos.

**Comment by SpencerCDixon** [comment]
No problem!  Know how it goes... thanks for all the work you put into this and virtualized.. much appreciated.
