### ISSUE TITLE
Pluggable search / index

### ISSUE THREAD

**Issue by ratson** [treasure-data/redux-search#40]
I am thinking if this could be used with [LokiJS](https://github.com/techfort/LokiJS), which provide different filtering and sorting option.

**Comment by bvaughn** [comment]
redux-search only ships with one search library, [js-worker-search](https://github.com/bvaughn/js-worker-search/). All of the interactions with this library though are encapsulated within a single adapter, [`SearchApi`](https://github.com/treasure-data/redux-search/blob/master/src/SearchApi.js). This adapter exposes the search interface as an observable. You can provide your own, custom `SearchApi` object so long as it implements [the same interface](https://github.com/treasure-data/redux-search/tree/master/docs#searchapi).

The [docs](https://github.com/treasure-data/redux-search/tree/master/docs#reduxsearch-resourceindexes-resourceselector-searchapi-searchstateselector-) actually mention this although they suggest it should only be done for testing purposes. You can see the [source code here](https://github.com/treasure-data/redux-search/blob/a458b0b7fe65674ba01e1099f7d9a8a1e38403b2/src/reduxSearch.js#L33) though where the override could happen.

**Comment by bvaughn** [comment]
I'm going to close this issue since what you've requested is already possible given the route I mentioned above. Feel free to ask more questions here though if what I've suggested is not clear.

**Comment by ratson** [comment]
I have read about the `SearchApi`, but still not sure if `LokiJS` could take advantage by implementing the interface, as `LokiJS` keeps its own index.

Anyway, thank you for your help. I am going to implement the search using `LokiJS` directly.

**Comment by bvaughn** [comment]
You would just need to provide an adapter that sits between LokiJS and redux-search that met the redux-search interface and passed requests through to one or more LokiJS instances. (This is similar to what redux-search does for js-worker-search.)
