### ISSUE TITLE
Please clarify is redux-search compatible with React Native?

### ISSUE THREAD

**Issue by rturk** [treasure-data/redux-search#45]
Hi thanks for building and sharing such amazing code. 
Can you please clarify how searches are performed (role of search middleware) regarding web-worker?

**Comment by bvaughn** [comment]
redux-search listens for changes in searchable data within a redux store. When data changes, redux-search rebuilds a search index and updates the results for any existing searches. It also provides action-creators and selectors for ease of integration with redux.

As for the action search, redux-search uses another library, [js-worker-search](https://github.com/bvaughn/js-worker-search) to index data and perform the underlying searches. js-worker-search [detects if a user's browser supports web workers](https://github.com/bvaughn/js-worker-search/blob/master/src/SearchApi.js#L12) and falls back to indexing and searching on the UI thread if not.

Hope this answers your question. :)
