### ISSUE TITLE
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.

### ISSUE THREAD

**Issue by acomito** [treasure-data/redux-search#47]
I'm getting this error when I try to install. Any ideas why that is?

`(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.`

**Comment by acomito** [comment]
hmm... seems to be meteor specific. Installing with this works:

`npm install --save redux-search`

but this does not:

`meteor npm install --save redux-search`

**Comment by bvaughn** [comment]
I'm not familiar with meteor. Which versions of Node and Npm are being used in the above examples?

I believe the `process.nextTick` call is happening inside of Npm, although I think it's already been resolved on the Npm side via npm/npm/pull/13021 and released via 3.10.0.

**Comment by acomito** [comment]
I believe v5.3.0

I'm not sure why prefixing with meteor was causing an issue, but it works fine as of now with the normal npm install.

**Comment by bvaughn** [comment]
Which version of Npm? If you're not using 3.10.0, I think upgrading should resolve the issue for you. Give it a shot?

**Comment by bvaughn** [comment]
Closing this for now. Don't believe it's a redux-search issue. Can reopen if necessary. :)
