### ISSUE TITLE
Reducer breaks if action === undefined

### ISSUE THREAD

**Issue by lukehedger** [treasure-data/redux-search#51]
`reducer.js` throws an error when the action object is `undefined`. Haven't been able to figure out exactly where this action is dispatched but occurs directly after `@@redux/PROBE_UNKNOWN_ACTION` and before the second `@@redux/INIT` (Redux v3.0.5). Either way, should be simple to catch this exception?

https://github.com/treasure-data/redux-search/blob/master/source/reducer.js#L13

Happy to raise a PR to change:
```
export default function searchReducer (state = {}, { payload, type }) {
  ...
}
```

to:
```
export default function searchReducer (state = {}, { payload, type } = {}) {
  ...
}
```

What dya think?

**Comment by bvaughn** [comment]
Hmm... I don't think Redux action-creators should return `undefined`. If they are, it seems like it would indicate a problem, no?

That being said, it would be pretty easy to set a default value like you described so I'm not opposed to making the change. Feel free to submit a PR, sure! 😄

**Comment by lukehedger** [comment]
Yeah agreed - I think it must be coming from Redux directly as it occurs before INIT but I'm not 100% sure.

I'll make the change 😁

**Comment by lukehedger** [comment]
https://github.com/treasure-data/redux-search/pull/52

**Comment by bvaughn** [comment]
Thanks :)

**Comment by bvaughn** [comment]
2.3.1 just published
